#!/usr/local/bin/bash
#
# Copyright (C) Mellanox Technologies Ltd. 2001-2019.  ALL RIGHTS RESERVED.
# Copyright (C) UT-Battelle, LLC. 2014. ALL RIGHTS RESERVED.
# See file LICENSE for terms.
#

#
# UCX build for development.
# Full logging and an runtime checks.
#

basedir=$(cd $(dirname $0) && pwd)
export CC=${CC:=gcc}
export CXX=${CXX:=g++}
export CPPFLAGS=${CPPFLAGS:="-I/usr/local/include/libepoll-shim"}
export LDFLAGS=${LDFLAGS:="-L/usr/local/lib -lepoll-shim"}
$basedir/../configure \
	--enable-profiling \
	--enable-frame-pointer \
	--enable-stats \
	--enable-memtrack \
	--enable-fault-injection \
	--enable-debug-data \
	--enable-mt \
	--disable-numa \
	"$@"
